/**
 * GLOBAL_RENDER_STATIC
 *
 * These rules are NEVER generated by an LLM. They are hardcoded and mandatory.
 * The final prompt is assembled as:
 *   GLOBAL_RENDER_STATIC + product_context + variation
 */

export const GLOBAL_RENDER_STATIC = `You are compositing a product into a customer's room photo for ecommerce visualization.

IMAGE ROLES
- prepared_product_image: The product with transparent background. This is the exact item being sold.
- customer_room_image: The customer's real room photo. This must be preserved exactly.

MANDATORY RULES

1. ASPECT RATIO: Output must match the aspect ratio and full frame of customer_room_image exactly.

2. ROOM PRESERVATION: Change only what is required to realistically insert the product into customer_room_image. Keep everything else exactly the same — geometry, furnishings, colors, lighting, objects.

3. SINGLE COMPOSITE: Output a single photoreal image of customer_room_image with the product added naturally. Not a collage. Not a split view. Not a new room. Not a background swap.

4. SCALE DOWN, NEVER CROP: If the product would be cut off by the frame, reduce its scale slightly until the entire product is visible. Do not crop the product.

5. BACKGROUND DISCARD: The transparent background of prepared_product_image must be completely discarded. Only the product itself appears in the output.

6. IDENTITY PRESERVATION: Preserve the exact character of the product — natural patina, wood grain variations, surface imperfections, weathering marks. These are features, not flaws. Do not smooth, polish, or idealize.

7. NO INVENTED HARDWARE: For mirrors and framed items, preserve the exact frame, mounting hardware, and edge details from prepared_product_image. Do not add, remove, or modify hardware.

8. PHYSICAL REALISM: Correct perspective matching the room's camera angle. Accurate shadows based on room lighting. Proper occlusion where the product meets room surfaces. Reflections consistent with room environment (for reflective materials).

9. NO STYLIZATION: No filters, color grading, vignettes, or artistic effects. No text or logos.

Return only the final composed image.`;
