alter table if exists shop add column if not exists shop_name text;
alter table if exists shop add column if not exists contact_email text;
alter table if exists shop add column if not exists shopify_shop_id text;
alter table if exists shop add column if not exists offline_access_token_encrypted text;
alter table if exists shop add column if not exists access_scopes text[];
alter table if exists shop add column if not exists plan text default 'trial';
alter table if exists shop add column if not exists trial_ends_at timestamptz;
alter table if exists shop add column if not exists renders_quota integer default 50;
alter table if exists shop add column if not exists lifestyle_images_quota integer default 10;
alter table if exists shop add column if not exists billing_subscription_id text;
alter table if exists shop add column if not exists billing_status text default 'trial';
alter table if exists shop add column if not exists room_preview_enabled boolean default true;
alter table if exists shop add column if not exists debug_asset_retention_enabled boolean default false;
alter table if exists shop add column if not exists installed_at timestamptz default now();
alter table if exists shop add column if not exists uninstalled_at timestamptz;
alter table if exists shop add column if not exists created_at timestamptz default now();
alter table if exists shop add column if not exists updated_at timestamptz default now();

alter table if exists product_setup add column if not exists shop_id uuid references shop(id);
alter table if exists product_setup add column if not exists shopify_product_gid text;
alter table if exists product_setup add column if not exists shopify_product_handle text;
alter table if exists product_setup add column if not exists title text;
alter table if exists product_setup add column if not exists width_mm integer;
alter table if exists product_setup add column if not exists height_mm integer;
alter table if exists product_setup add column if not exists depth_mm integer;
alter table if exists product_setup add column if not exists category text;
alter table if exists product_setup add column if not exists material text;
alter table if exists product_setup add column if not exists colour text;
alter table if exists product_setup add column if not exists merchant_notes text;
alter table if exists product_setup add column if not exists primary_image_key text;
alter table if exists product_setup add column if not exists cutout_key text;
alter table if exists product_setup add column if not exists prep_status text default 'none';
alter table if exists product_setup add column if not exists enabled boolean default false;
alter table if exists product_setup add column if not exists created_at timestamptz default now();
alter table if exists product_setup add column if not exists updated_at timestamptz default now();

alter table if exists room_session add column if not exists shop_id uuid references shop(id);
alter table if exists room_session add column if not exists product_setup_id uuid references product_setup(id);
alter table if exists room_session add column if not exists source text default 'widget';
alter table if exists room_session add column if not exists room_key text;
alter table if exists room_session add column if not exists normalized_room_key text;
alter table if exists room_session add column if not exists verified boolean default false;
alter table if exists room_session add column if not exists width integer;
alter table if exists room_session add column if not exists height integer;
alter table if exists room_session add column if not exists expires_at timestamptz;
alter table if exists room_session add column if not exists created_at timestamptz default now();
alter table if exists room_session add column if not exists last_activity_at timestamptz default now();

alter table if exists render_feedback add column if not exists render_request_id uuid references render_request(id);
alter table if exists render_feedback add column if not exists verdict text;
alter table if exists render_feedback add column if not exists issue_tag text;
alter table if exists render_feedback add column if not exists comment text;
alter table if exists render_feedback add column if not exists created_at timestamptz default now();

alter table if exists event_log add column if not exists ts timestamptz default now();
alter table if exists event_log add column if not exists surface text;
alter table if exists event_log add column if not exists name text;
alter table if exists event_log add column if not exists shop_id uuid;
alter table if exists event_log add column if not exists prospect_id uuid;
alter table if exists event_log add column if not exists render_request_id uuid;
alter table if exists event_log add column if not exists product_setup_id uuid;
alter table if exists event_log add column if not exists ai_invocation_id uuid;
alter table if exists event_log add column if not exists props_json jsonb default '{}';
